### ISSUE TITLE
NetToPLCSim - Not in the documentation - Only a Windows package for PLC simulation - Not for linux

### ISSUE THREAD

**Issue by federico22285** [miguelob/ICS-Hacking#10]
Hello, Thank you for your feedback so far! 

I wanted to proceed to test the code but I came up with this line of code: 

IP = '192.168.1.10' #Ip of the PLC inside NetToPLCSim (Change to your PLC IP)

If I understand correctly for your code to work I have to install an emulator of PLC - This is what NetToPLCSim will do for me BUT this is a Windows-only package... 

Thanks!

**Comment by federico22285** [comment]
Ok - This is a little update, I have installed two different versions of NetToPLCSim on windows ( the version from 2018 and the latest one from 2021 ) both are failing when I change the IP address in the SCADA python script. I think that the issue is somehow in the communication. If you try that out you will be getting an issue with t dll on NetToPLCSim side.

**Comment by miguelob** [comment]
hi @federico22285,
Thanks for your feedback. I have tested the code with a windows machine and NetToPLC and it worked. However it should work with any PLC simulator. Try to execute the SCADA LAB of the packet (download repo, go into packet folder, execute main.py, install requirements, and execute SCADA LAB inside the packet GUI). Let me know if that works.

In addition, the NetToPLC its hard sometimes to get it working inside your network. Make sure that the program is working properly inside your network (I recommend to use Wireshark to check it) and change between your card and the virtual NetToPLC network card to see which one is inside you local network.

Also make sure that you have the snap7 python package and the Windows snap7.dll or the MacOS equivalent (install with brew).

**Comment by miguelob** [comment]
solved
