### ISSUE TITLE
Error running main.py

### ISSUE THREAD

**Issue by espyerx-x** [miguelob/ICS-Hacking#11]
I have install the new release .zip
It is saying in Discovery.py that name mac is not defined at 
class Discovery(mac):
![image](https://github.com/miguelob/ICS-Hacking/assets/82972589/46ea3911-dafc-408d-815f-0bf79327bff7)

**Comment by miguelob** [comment]
@m-raheem Ok I will work on the fix and let you know in this issue when its fixed. Thanks for letting me know =D
You are running the main from the package or directly the one in the repo?

**Comment by espyerx-x** [comment]
Sure Thank you + I'm running main from the release package

**Comment by miguelob** [comment]
@m-raheem Sorry for my late response. I had to migrate the project from one cloud to another. I can now work on the fix. Ill contact you asap

**Comment by espyerx-x** [comment]
Sure. My BAS is relying on this much XD.

**Comment by miguelob** [comment]
@m-raheem are you using the last version available? I just run that version and everything works fine. LMK with any update

**Comment by espyerx-x** [comment]
Im using the latest version the zip provided in release. And it isn't
working for me.

**Comment by miguelob** [comment]
ok. @m-raheem can you send me the zip file that you are using and some more information to debug the issue (OS, version, requirements versions, etc)?

**Comment by miguelob** [comment]
Closing issue due to the lack of information
