### ISSUE TITLE
Issue: name 'plc' is not defined when running SCADA_LAB.py

### ISSUE THREAD

**Issue by federico22285** [miguelob/ICS-Hacking#4]
Hello there, 

It seems that it is not working for me, what python version you have installed for this to work?, which versions of each package? :-) 

```
  File "/Users/federico/Downloads/ICS-Hacking-main/SCADA/SCADA_LAB.py", line 6, in <module>
    class GUI(plc, client):
NameError: name 'plc' is not defined
```

**Comment by charliehernandez97** [comment]
I am also having this issue. There are multiple variables that are undefined in the repository. I downloaded the latest repository (version 1.0) and it had the same issues. In Discovery.py and FlashLED.py, Ether(raw_pkt) is also undefined - I tried looking it up on google but there weren't any libraries that contained it. The only results I got involved ethereum. Attached are the errors that are showing up on VSCode
![undefined variables](https://user-images.githubusercontent.com/28545535/189779023-e180ffed-5cc3-417d-a6c8-1daf9d244803.png)

**Comment by miguelob** [comment]
@federico22285 @charliehernandez97 I'll work on fixing the issues for a week and ill come back to you when it is solved. Thanks for letting me know these bugs.

**Comment by charliehernandez97** [comment]
> @federico22285 @charliehernandez97 I'll work on fixing the issues for a week and ill come back to you when it is solved. Thanks for letting me know these bugs.

Thank you Miguel! Really appreciate all the work you are doing. You rock

**Comment by miguelob** [comment]
> Hello there,
> 
> It seems that it is not working for me, what python version you have installed for this to work?, which versions of each package? :-)
> 
> ```
>   File "/Users/federico/Downloads/ICS-Hacking-main/SCADA/SCADA_LAB.py", line 6, in <module>
>     class GUI(plc, client):
> NameError: name 'plc' is not defined
> ```

@federico22285 Check this last commit. I have only fixed this [file](https://github.com/miguelob/ICS-Hacking/blob/main/SCADA/SCADA_LAB.py). I do not have the equipment to try it, so let me know if everything is working now and I'll apply the fix to the package. In the code you must need to change some IP addresses and 

About the packages, all are listed on read.me and you can find the requirements.txt on the package folder (with the versions already in it), so you just have to pip3 install -r requirements.txt.

**Comment by miguelob** [comment]
sorry, I have close the issue by an error, I reopen It

**Comment by miguelob** [comment]
> I am also having this issue. There are multiple variables that are undefined in the repository. I downloaded the latest repository (version 1.0) and it had the same issues. In Discovery.py and FlashLED.py, Ether(raw_pkt) is also undefined. Attached are the errors that are showing up on VSCode
> Edit: I made sure to install all the requirements, but still no luck
> ![undefined variables](https://user-images.githubusercontent.com/28545535/189779023-e180ffed-5cc3-417d-a6c8-1daf9d244803.png)

@charliehernandez97 I have moved your issue to another issues page. Check it out with the new version that I have upload. [Link to the issue page](https://github.com/miguelob/ICS-Hacking/tree/main/packet)

**Comment by miguelob** [comment]
@federico22285 I'm still working on the fix. It will take more time than expected, but I'll have it asap.

**Comment by federico22285** [comment]
@miguelob Thanks for the feedback Miguel, would be great to see this project working. Just wondering how you have make it work initially, was it python 2.7 (?) was it specific versions of the required packages(?) i.e installing version 1.2.3 from package XYZ.

Anyway would be great to see this project working and please let me know if there is anything I can do to help you out :)

**Comment by miguelob** [comment]
@federico22285 this project was initially private and I used it as a research for my final degree project. So all python classes and the modules just worked with real life PLCs and with my personal IPs. So now that the project is open to everyone and that I'm integrating everything in just one executable, many things should be changed, so I'm in that state of the development.

**Comment by miguelob** [comment]
Hi @federico22285  a new commit was released. Try and check it out and see if it fix the issue. A new release package is not launched so you might get the new version from the [packet folder](https://github.com/miguelob/ICS-Hacking/tree/main/packet) in the repo.

**Comment by miguelob** [comment]
Ill close this issue as now its duplicated with an older one regarding the same bug. Any news on the topic, feel free to create a new issue or use the existing one for this bug.

Have a nice day 😃.
