### ISSUE TITLE
Ether not working on Profinet and Profibus (version 1.0)

### ISSUE THREAD

**Issue by miguelob** [miguelob/ICS-Hacking#5]
I am also having this issue. There are multiple variables that are undefined in the repository. I downloaded the latest repository (version 1.0) and it had the same issues. In Discovery.py and FlashLED.py, Ether(raw_pkt) is also undefined. Attached are the errors that are showing up on VSCode
Edit: I made sure to install all the requirements, but still no luck
![undefined variables](https://user-images.githubusercontent.com/28545535/189779023-e180ffed-5cc3-417d-a6c8-1daf9d244803.png)

_Originally posted by @charliehernandez97 in https://github.com/miguelob/ICS-Hacking/issues/4#issuecomment-1244727444_

**Comment by miguelob** [comment]
Check last commit. I have fixed the profinet and profibus on the package module. Let me know if everything is working now. I'm not going to post the new version until im sure that everything is working, so you can find the new temp package in this link on the repo [package link](https://github.com/miguelob/ICS-Hacking/tree/main/packet).

Also reinstall the packages on requirements.txt because I have upgrade it.

When running the code, now you will be also asked to type the name of the interface that you will be using for sending the packages.

Any bug or recommendation, pls let me know.

**Comment by charliehernandez97** [comment]
> Check last commit. I have fixed the profinet and profibus on the package module. Let me know if everything is working now. I'm not going to post the new version until im sure that everything is working, so you can find the new temp package in this link on the repo [package link](https://github.com/miguelob/ICS-Hacking/tree/main/packet).
> 
> 
> 
> Also reinstall the packages on requirements.txt because I have upgrade it.
> 
> 
> 
> When running the code, now you will be also asked to type the name of the interface that you will be using for sending the packages.
> 
> 
> 
> Any bug or recommendation, pls let me know.

Thanks a lot Miguel, I will report back to you
